### ISSUE TITLE
Unity 2017.3.1 Compatibility

### ISSUE THREAD

**Issue by ddutchie** [ActiveNick/Unity-MS-SpeechSDK#2]
Thanks for this. Great learning project. 

Is there a reason for using Unity 2018.
I have tried using 2017.3 and am running into some issues.

**Comment by ActiveNick** [comment]
There's a couple reasons why this is built on 2018.2:

- The access to the Speech SDK is done over native WebSocket classes in .NET 4.6. Support for .NET 4.6 was experimental in 2017.x, now released as stable in 2018.x.
- Most Azure cloud services require secure SSL/TLS connections. Unity 2018.1 and before doesn't support TLS since it has no way to verify certificates using local certificate stores. This was finally fixed in 2018.2. This sample also requires a secure TLS connection, hence why it won't work in 2018.1 or 2017.x even if you have a valid API key. There is a hack to get around this in these older versions, but it is not secure or production-ready, which is why we don't advocate using it now that 2018.2 is out.

**Comment by ddutchie** [comment]
I thought it had to do with TLS but could not get up and running. Time to upgrade to 2018.2! Thanks for explaining.
